name: Remote SSH
on: [push]
jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USERNAME}}
          password: ${{secrets.DEV_PASSWORD}}
          script: |
            cd ton-task-manger
            git stash
            ${{ secrets.DEV_SCRIPT }}
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18
            npm i --legacy-peer-deps
            npm run build
            pm2 restart ton-task-manger
  prod:
    name: prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          script: |
            cd ton-task-manger
            git stash
            ${{ secrets.SCRIPT }}
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18
            npm i --legacy-peer-deps
            npm run build
            pm2 restart ton-task-manger
